[ADD] python 3.10 and 3.11 to install and update scripts

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -24,12 +24,12 @@ install_clt() {
 
   info "Trying to detect installed Command Line Tools for Xcode..."
 
-  xcode-select -p &> /dev/null
+  xcode-select -p &>/dev/null
   if [ $? -ne 0 ]; then
     info "Installing Command Line Tools for Xcode..."
-    touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress;
+    touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
     PROD=$(softwareupdate -l | grep "\*.*Command Line" | tail -n 1 | sed 's/^[^C]* //')
-    softwareupdate -i "$PROD" --verbose;
+    softwareupdate -i "$PROD" --verbose
   else
     success "You already have Command Line Tools for Xcode installed. Skipping..."
   fi
@@ -78,22 +78,29 @@ install_software() {
 }
 
 install_python() {
-  if ! _exists python3.11; then
-    info "Installing Python..."
+  if [ $# -ne 1 ]; then
+    echo "Usage: install_python <version>"
+    return
+  fi
+
+  version=$1
+
+  if ! _exists python@$version; then
+    info "Installing Python $version..."
 
     if [ "$(uname)" = "Darwin" ]; then
-      /opt/homebrew/bin/brew install python@3.11
-      /opt/homebrew/bin/brew link --overwrite python@3.11
+      /opt/homebrew/bin/brew install python@$version
+      /opt/homebrew/bin/brew link --overwrite python@$version
     elif [ "$(uname)" = "Linux" ]; then
       sudo apt install wget build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
       sudo add-apt-repository ppa:deadsnakes/ppa
-      sudo apt install python3.11
+      sudo apt install python$version
     else
-      error "Error: Failed to install python3.11!"
+      error "Error: Failed to install Python $version!"
       exit 1
     fi
   else
-    success "You already have Python installed. Skipping..."
+    success "You already have Python $version installed. Skipping..."
   fi
 
   packages=(
@@ -101,7 +108,7 @@ install_python() {
     poetry
   )
   echo "Installing: ${packages[*]}"
-  python3.11 -m pip install --upgrade "${packages[@]}"
+  python$version -m pip install --upgrade "${packages[@]}"
 
   finish
 }
